### ISSUE TITLE
Move to setup.cfg / pyproject.toml

### ISSUE THREAD

**Issue by lebigot** [lmfit/uncertainties#147]
In 2021, setup.cfg + pyproject.toml is more modern than setup.py. It wouldn't hurt to move to these more recent configurations (now that there is no complicated build for the Python 2 / Python 3 compatibility).

**Comment by neutrinoceros** [comment]
Here's a tool that can do the heavy lifting here
https://pypi.org/project/setup-py-upgrade/

**Comment by wshanks** [comment]
Done in #199
