### ISSUE TITLE
code coverage not uploading for master branch

### ISSUE THREAD

**Issue by jagerber48** [lmfit/uncertainties#204]
The code coverage is not uploading for the master branch. I'm not sure what the issue is. It's possibly something with the github apps settings on the repo. I can access some of these, but I'm blocked out of some because I'm not an lmfit owner.

**Comment by newville** [comment]
@jagerber48 Hmm, not 100% what's happening, either.  I have don't have a lot of experience with codecov.   
I updated the webhook for codecov to "send everything", and reset the "secret" (to be blank)...
Do you know what the token at
``` 
token: ${{ secrets.CODECOV_TOKEN }}
```

is supposed to be?

**Comment by jagerber48** [comment]
Ok thanks for trying that. That secret was something I set up  based on the codecov instructions when I was first configuring the codecov GitHub application. 

I don’t have a chance to look into it now but I’ll try in the next few days if I get a chance.

**Comment by newville** [comment]
@jagerber48 okay, I am not that familiar with codecov setup. Hopefully we can figure it out eventually.

**Comment by jagerber48** [comment]
I reset the secret. If I log on to codecov.io using github account there is an option to see my organizations which include `lmfit`, then I can find the `uncertainties` repo and under settings there is the codecov token. I set the secret back to that value. We'll see on the next commit or merge that happens in the repo if that helps get the master branch coverage updated. If that doesn't work, or in the meantime, I'll research the issue more.

**Comment by jagerber48** [comment]
Sorry, just updated the token now

**Comment by jagerber48** [comment]
It looks like some of the accidental pushes to master kicked codecov into reading the coverage on the master branch. I'll monitor that codecov looks ok after a few PRs actually get merged and if it all looks good I'll close this issue.
