### ISSUE TITLE
Lacks basic VSCode settings for running pytest tests with VSCode.

### ISSUE THREAD

**Issue by willynilly** [lmfit/uncertainties#206]
The code lacks the basic settings to easily run tests using pytest within VSCode.

**Comment by willynilly** [comment]
Here's my pull request: https://github.com/lmfit/uncertainties/pull/205

**Comment by andrewgsavage** [comment]
I haven't seen these settings included in any other python libraries, so I'm not sure whether this is something we should add

**Comment by wshanks** [comment]
The tests were written for nose. In #194, we "transitioned" to pytest by removing the old Travis and AppVeyor config files and adding a GitHub Actions workflow that calls pytest, which just worked without any other changes to the tests. We wanted to follow up with further clean up of the tests (and rest of the code). Would adding some minimal configuration for pytest be enough for VSCode to figure out that the tests should be run with pytest? Like @andrewgsavage, I wonder if that is how it usually works with other projects that don't have a `.vscode` directory.

**Comment by newville** [comment]
I don't understand why "easily run tests using pytest within VSCode" is something that this library needs to support.  

I suggest adding `.vscode` to `.gitignore`.  That would allow individuals to add such configurations to their own copies of the repository without being pushed to the master branch.

**Comment by willynilly** [comment]
I made the case for including some default VSCode settings in the comments here: https://github.com/lmfit/uncertainties/pull/205
In a nutshell, I think these settings facilitate testing.  My argument did not persuade the maintainer. That's fine.  I can always create a seperate tiny repo with default IDE settings to help facilitate testing.  

So my understanding, per @newville, that this repo will not include any default IDE setting files for VSCode. Here's a pull request to add .vscode to the .gitignore file: https://github.com/lmfit/uncertainties/pull/212

**Comment by willynilly** [comment]
I have a created a separate repo with the default IDE settings for VSCode here: https://github.com/willynilly/uncertainties-default-ide-settings

If anyone has some default IDE settings that they think will help others more easily test and/or develop the code, feel free to send me a pull request to this repo with those settings and I will try to add them.
