### ISSUE TITLE
Plotting data with error bars/band?

### ISSUE THREAD

**Issue by SjoerdOptLand** [lmfit/uncertainties#26]
I am not sure whether this belongs in `uncertainties` (in order to keep it light and with few external dependencies), but I wanted to visualise uncertain measurement data and had to come up with a snippet like this.

In my experience, having visualizing tools handy really helps in development and debugging, which might be an argument in favor of creating a `uplot` module (and only this module requiring matplotlib). Other error visualisation (tool tips showing the chain, tags, ...) may be less trivial and useful to share.

What do others think?

``` python
from matplotlib import pyplot
from uncertainties import unumpy

def plot(x,y,*args,**kwargs):
    nominal_curve = pyplot.plot(x, unumpy.nominal_values(y), *args, **kwargs)
    pyplot.fill_between(x, 
                        unumpy.nominal_values(y)-unumpy.std_devs(y), 
                        unumpy.nominal_values(y)+unumpy.std_devs(y),
                        facecolor=nominal_curve[0].get_color(),
                        edgecolor='face',
                        alpha=0.1,
                        linewidth=0)
    return nominal_curve

if __name__ == '__main__':
    import numpy
    from uncertainties import ufloat
    x = numpy.linspace(0, 15, 120)

    eps = ufloat(0,0.4)
    y = unumpy.sin((x+eps)/6*numpy.pi)

    plot(x,y,'r--',label='sine')
    pyplot.legend()
    pyplot.show()
```

**Comment by RokoMijic** [comment]
Right now using uncertainties with matplotlib typically results in an error from matplotlib, rather than the desired result of whatever plot you would have got, but with error bars. 

I discovered the uncertainties module about 90% of the way through hacking together similar functionality myself for an ipython/Jupyter data analysis project. It is extremely helpful, and it would be a real killer feature if it played nicely with simple graphing from matplotlib.

**Comment by lebigot** [comment]
I am not sure what approach would be best.

Currently, plotting numbers with uncertainty `y` with error bars is as simple as:
`pyplot.errorbar(x, unumpy.nominal_values(y), yerr=unumpy.nominal_values(y))`, so I don't feel the need to create any specific library for this. Plus, users can really customize their plots using regular Matplotlib/Seaborn/plot.ly, with this approach.

Now, I could think of simplifying this to:
`pyplot.errorbar(x, y.n, yerr=y.s)` by implementing a specific NumPy array subclass instead of piggy-backing on the standard NumPy array class.

What do you think?

**Comment by RokoMijic** [comment]
@lebigot well the ideal experience would be if feeding ufloats to `plt.scatter` just made it make a plot with error bars, like magic. However I realize that that would involve changing the matplotlib/pyplot code (and given the flexibility of plotting, it might be hard to come up with a solution that covered enough cases with sensible default behavior). 

Beware of trivial inconveniences: people are lazy. It would be nice if the libraries worked together seamlessly to do something sensible. Look at the difference in effort here (and is the second one documented anywhere?):

`plt.scatter(x_deterministic,y_deterministic)`

versus

`
from uncertainties import unumpy
plt.errorbar( unumpy.nominal_values(x_ufloats), unumpy.nominal_values(y_ufloats),  xerr=unumpy.std_devs(x_ufloats), yerr= unumpy.std_devs(y_ufloats), fmt='o')  
`

Do you think it is likely that the owners of matplotlib would accept a pull request for for code that adds error bars to certain plot functions if ufloats are supplied as data without explicit error bar parameters?

**Comment by rth** [comment]
> Do you think it is likely that the owners of matplotlib would accept a pull request for for code that adds error bars to certain plot functions if ufloats are supplied as data without explicit error bar parameters?

That doesn't sound very likely in my opinion..

**Comment by RokoMijic** [comment]
As a bonus, it would be nice to have `ufloat` versions of `np.polyfit` and `np.poly1d` that actually do something statistically sensible in terms of calculating a linear best fit. Right now all you can do is calculate a best fit line using `unumpy.nominal_values`, which is statistical nonsense.

**Comment by rth** [comment]
> As a bonus, it would be nice to have ufloat versions of np.polyfit and np.poly1d that actually do something statistically sensible in terms of calculating a linear best fit. 

Maybe, one can use [`scipy.odr`](https://docs.scipy.org/doc/scipy/reference/odr.html) to estimate the uncertainty on the fit coefficients (which would also work for non-polynomial functions)..  Though scipy is not a dependency of `uncertainties`, so it might have to be a separate function..

**Comment by hornekyle** [comment]
I'd like to second the request for implementations of polyfit and poly1d for use with ufloat data. I teach an experiments class and would like things to be easier for my students.

**Comment by lebigot** [comment]
The additional capabilities listed here are certainly useful.

I could imagine them being implemented in some "uncertainties utilities" library that contains a few specific functions that would act as drop-ins for existing plotting/fitting functions, but with an added `uncertainties` compatibility. Maybe importable with something like `from uutilities.unumpy import polyfit`.

I must say that I never had to use my own module much; instead I worked hard on it and gave it a lot of love. :) So, creating these functions that add support for numbers with uncertainties is a task that I encourage the community of users to take up. I would do my best to contribute too.

**Comment by nilnil47** [comment]
Hi,
I am a Physics student and really want to use the feature discussed above,
Is there any progress with these / alternatives that have these features?

Thank you very much!

**Comment by lebigot** [comment]
I haven't heard of this yet, but I'd be curious to learn if someone released an uncertainty-aware library that does this, too.

**Comment by hornekyle** [comment]
Since my last comment (years ago) I have written a few different versions of uncertainty aware linear regression functions. Maybe we should make a list of desired functions and share what we have?
